### ISSUE TITLE
[Feature] Rotate display 90 degrees or 180 degrees

### ISSUE THREAD

**Issue by philletourneau** [Igalia/balena-wpe#17]
**Is your feature request related to a problem? Please describe.**
I would like the ability to rotate the entire display 90 or 180 degrees. I've attempted to set the built-in Balena device configuration to rotate the display, but it doesn't appear to work with the Weston/WPE environments.

**Describe the solution you'd like**
I would either like an option within this project to rotate the display, or a suggestion for how to accomplish this some other way.

**Describe alternatives you've considered**
I've tried the Balena configuration option for rotating the display on a Raspberry Pi

**Additional context**
I'm using a Raspberry Pi 4 with the most recent BalenaOS

**Comment by H31nz3l** [comment]
Hey! I was struggling with custom resolutions and rotations as well. I tried the config.txt environment settings to rotate the display, as well as setting the hdmi_mode. None of these settings have an impact on the displayed screen. It appears that the Weston display manager overrules these settings.

**Comment by philletourneau** [comment]
@H31nz3l I just discovered this, was going to see if I can edit this configuration file somehow to accomplish this. https://developer.technexion.com/docs/change-screen-rotation-in-waylandweston-desktop

I'm new to Balena.io and Docker, but this looks promising.

**Comment by H31nz3l** [comment]
Sounds great. Looks promising indeed. I'll try it next week.

**Comment by philletourneau** [comment]
@H31nz3l I figured it out!  😄 

In the `weston-init` file in the `weston` directory, I added a new section below `[shell]` with the following lines

```
[output]
name=HDMI-A-1
mode=3840x1920@60
transform=rotate-90
```

**Comment by philletourneau** [comment]
Working as expected! :)
